=begin
  Each new term in the Fibonacci sequence is generated by adding the previous two terms.
  By starting with 1 and 2, the first 10 terms will be:
  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
  By considering the terms in the Fibonacci sequence whose values do not exceed four million,
  find the sum of the even-valued terms.
=end

def fibonacciSumEven(num)
  evenSum = 0
  fibonacciSum = 0
  prevFibonacci = 0
  currentFibonacci = 1
  i = 0
  loop do
    fibonacciSum = prevFibonacci + currentFibonacci
    prevFibonacci = currentFibonacci
    currentFibonacci = fibonacciSum
    if fibonacciSum % 2 === 0 && fibonacciSum <= num
      evenSum += fibonacciSum
    end
    break if fibonacciSum > num
  end
  evenSum
end

puts fibonacciSumEven(4000000)
